version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      ci-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
    commit-message:
      prefix: "ci: "
