from pathlib import Path

import pytest

from correctionlib import CorrectionSet

CVMFS_ROOT = Path("/cvmfs/cms-griddata.cern.ch/cat/metadata")

pytestmark = [
    pytest.mark.cvmfs,
    pytest.mark.skipif(
        not CVMFS_ROOT.exists(),
        reason="CVMFS is not available in this environment",
    ),
]


@pytest.fixture(
    scope="module",
    params=[
        # make relative for display purposes
        str(path.relative_to(CVMFS_ROOT))
        # structure: POG / Campaign / Tag / JSON file
        for path in CVMFS_ROOT.glob("*/*/latest/*.json.gz")
    ],
)
def cvmfs_correction(request) -> str:
    return str(CVMFS_ROOT / request.param)


def test_load(cvmfs_correction: str, benchmark):
    # warm up (download file)
    CorrectionSet.from_file(cvmfs_correction)

    benchmark(CorrectionSet.from_file, cvmfs_correction)


# TODO: evaluate with autogenerated data and measure performance
