from pathlib import Path

import pytest

CVMFS_ROOT = Path("/cvmfs/cms-griddata.cern.ch/cat/metadata")

pytestmark = [
    pytest.mark.cvmfs,
    pytest.mark.skipif(
        not CVMFS_ROOT.exists(),
        reason="CVMFS is not available in this environment",
    ),
]


@pytest.fixture(
    scope="module",
    params=[
        # make relative for display purposes
        str(path.relative_to(CVMFS_ROOT))
        for path in CVMFS_ROOT.glob("**/*.json.gz")
    ],
)
def cvmfs_correction(request) -> str:
    return str(CVMFS_ROOT / request.param)


def test_validate_correction(cvmfs_correction: str, benchmark):
    from correctionlib import CorrectionSet

    benchmark(CorrectionSet.from_file, cvmfs_correction)


# TODO: evaluate with autogenerated data and measure performance
