name: Docs

on:
  workflow_dispatch:
  push:
    branches:
    - master
    - main

jobs:
  docs:
    name: Build and deploy docs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install package
      run: python -m pip install -e .[docs]

    - name: Build documentation
      run: |
        cd docs
        make
        touch build/html/.nojekyll

    - name: Deploy documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/html
